#
# Macro file for "Hadr04.cc"
# (can be run in batch, without graphic)
#
# neutron 2 MeV; all processes
#
/control/verbose 2
/run/verbose 2

/run/initialize
#
/process/list
#
/gun/particle neutron
/gun/energy 2.5 MeV
#
/analysis/setFileName test01
/analysis/h1/set 1  100  0. 100. none	#nb colli >1eV
/analysis/h1/set 2  100  0. 100. cm	#track len >1eV
/analysis/h1/set 3  100  0. 5. us	#time of flight >1eV
/analysis/h1/set 4  100  0. 1000. none	#nb colli <1eV
/analysis/h1/set 5  100  0. 500. cm	#track len <1eV
/analysis/h1/set 6  100  0. 1000. us	#time of flight <1eV
/analysis/h1/set 7  100  0. 500. meV	#energy dist <1eV
#
/run/printProgress 200
#
/run/beamOn 2000
